# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- script: |
    # Esto es un script para copiar los archivos HTML y CSS de tu repositorio a la carpeta de publicación
    cp -r portafolio/* $(Build.ArtifactStagingDirectory)
  displayName: 'Copiar archivos HTML y CSS'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'web-app'
    publishLocation: 'Container'
  displayName: 'Publicar archivos de la aplicación web'
